kind: Service
apiVersion: v1
metadata:
  name: oidc-server-public
  namespace: oidc-mock
spec:
  selector:
      app: server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 6999
  type: NodePort
