#!/bin/bash

## We used to use the package version in repo "github.com/aporeto-inc/regodux"
## but this was archived and is no longer maintained.

## I created this file to generate the versions file at
## "<repo>/internal/versions/versions.go"

VERSION_FILE="$1"

export VERSION="$2"
export PROJECT_NAME="$3"
export PROJECT_SHA="$4"
export PROJECT_BRANCH="$5"
export PROJECT_REVISION="$6"

cat > "${VERSION_FILE}" <<!TEMPLATE!
// *********************************************************
// ***              DO NOT EDIT THIS FILE                ***
// ***  --- Auto-generated from scripts/mkversion.sh --- ***
// *********************************************************

package versions

import "fmt"

// Project is the name of the project
const ProjectName = "${PROJECT_NAME}"

// ProjectVersion is the version of ${PROJECT}
const ProjectVersion = "${VERSION}"

// ProjectSha is the revision of ${PROJECT}
const ProjectSha = "${PROJECT_SHA}"

// ProjectBranch is the current branch name
const ProjectBranch = "${PROJECT_BRANCH}"

// ProjectRevision is the current revision name (includes dirty marker)
const ProjectRevision = "${PROJECT_REVISION}"

func GetVersions() (string) {
    return fmt.Sprintf("v%s - %s (%s)", ProjectVersion, ProjectBranch, ProjectRevision)
}
!TEMPLATE!

